version: '3.8'

services:
  
  autoatendimento-database:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD 
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysqlvolume:/var/lib/mysql


  autoatendimento:
    depends_on:
      - autoatendimento-database    
    
    build:
      context: ./
      dockerfile: dockerfile
    working_dir: /usr/src/autoatendimento
    container_name: autoatendimento-app
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://autoatendimento-database:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2  
    stdin_open: true
    tty: true
  
volumes:
    mysqlvolume:
     